### ISSUE TITLE
Stageless payload creation

### ISSUE THREAD

**Issue by Simon-Davies** [MythicAgents/Apollo#102]
Can you add the ability to create a stageless payload please.

**Comment by djhohnstein** [comment]
All Apollo payloads are stageless, if by stageless you mean having the full agent being delivered to target. There is no notion of stage 0, 1, 2, etc. unless you impose it yourself with creating a 'thin' agent with only the load command.

**Comment by Simon-Davies** [comment]
@djhohnstein Thank you.
