### ISSUE TITLE
Issues installing apollo and athena on kali linux

### ISSUE THREAD

**Issue by sly9it** [MythicAgents/Apollo#108]
Gives the deb.debian.org resolve issue

The c# agents are a hassle to fix

**Comment by checkymander** [comment]
What specific error do you get? And how are you installing them? The build should be handled inside of a docker container and shouldn't require you to do anything specific.

**Comment by djhohnstein** [comment]
This flew under my radar while I was on vacation. It sounds like the docker container or the Mythic instance doesn't have internet connectivity or is unable to resolve DNS.
