### ISSUE TITLE
Error building with Download 

### ISSUE THREAD

**Issue by v1stra** [MythicAgents/Apollo#146]
Today I'm getting some build errors when building with the download and upload modules in the payload. 

I think the relevant errors are here:

```
/tmp/tmpkqzixsfu89efc483-ef4e-4bc9-9e2f-a08ead608166/Tasks/upload.cs(20,18): error CS0101: The namespace 'Tasks' already contains a definition for 'download' [/tmp/tmpkqzixsfu89efc483-ef4e-4bc9-9e2f-a08ead608166/Tasks/Tasks.csproj]
/tmp/tmpkqzixsfu89efc483-ef4e-4bc9-9e2f-a08ead608166/Tasks/upload.cs(38,16): error CS0111: Type 'download' already defines a member called 'download' with the same parameter types [/tmp/tmpkqzixsfu89efc483-ef4e-4bc9-9e2f-a08ead608166/Tasks/Tasks.csproj]
/tmp/tmpkqzixsfu89efc483-ef4e-4bc9-9e2f-a08ead608166/Tasks/upload.cs(43,30): error CS0111: Type 'download' already defines a member called 'Start' with the same parameter types [/tmp/tmpkqzixsfu89efc483-ef4e-4bc9-9e2f-a08ead608166/Tasks/Tasks.csproj]
/tmp/tmpkqzixsfu89efc483-ef4e-4bc9-9e2f-a08ead608166/Tasks/upload.cs(22,10): error CS0579: Duplicate 'DataContract' attribute [/tmp/tmpkqzixsfu89efc483-ef4e-4bc9-9e2f-a08ead608166/Tasks/Tasks.csproj]
```

I was able to easily reproduce this by attempting to build a payload with only the Download module in it.

**Comment by its-a-feature** [comment]
Good catch! A new version is building as we speak (check the Actions tab at the top). Something happened and the `Download` code was copied in for both `Download` and `Upload`. I swapped it back to actually have the `Upload` code and it's building now

**Comment by its-a-feature** [comment]
It should be fixed now. If you can do `sudo ./mythic-cli install github https://github.com/mythicagents/apollo -f` and then try building apollo again, it should work that time.

**Comment by v1stra** [comment]
I just tested with a fresh install and it works. Thanks for the quick fix
