### ISSUE TITLE
User Agent Key Not Populating

### ISSUE THREAD

**Issue by Antonlovesdnb** [MythicAgents/Apollo#41]
When I create an Apollo payload the User Agent shows up as the literal string "_USER_AGENT_" instead of the value of the User-Agent key in the headers section of the C2 profile.

An example of a redirector log: 

`1.1.1.1 - - [06/Jul/2021:17:47:14 +0000] "POST /bah/bah/bah HTTP/1.1" 200 753 "-" "USER_AGENT"`

Please let me know if you need more information - thanks very much!

**Comment by djhohnstein** [comment]
I'm on it!

**Comment by Antonlovesdnb** [comment]
> I'm on it! This is an artifact of migrating to the latest version. Sorry about that.

No need to be sorry at all! Thanks for taking a look 👍
