### ISSUE TITLE
Unable to Execute Apollo via Assembly Load

### ISSUE THREAD

**Issue by getshellz** [MythicAgents/Apollo#77]
Apollo wasn't playing nice when being loaded in via assembly load, managed to figure out the issue was that the `Main` was being set to `private`.  

Was able to get it to work by just simply editing the `Main` to be `public` shown here:

https://github.com/getshellz/Apollo/blob/master/Payload_Type/apollo/agent_code/Apollo/Program.cs#L40 

Not sure if you count it as an issue

**Comment by djhohnstein** [comment]
I sure can. I'll patch it in today 🙂
