### ISSUE TITLE
Plain Text mode

### ISSUE THREAD

**Issue by vikingtwtw** [MythicAgents/Apollo#90]
Is plain text mode supported when Mythic configures the Payload with "Crypto Type" as "None" and "Perform Key Exchange" as "F"? The agent appears to encounter an error when it tries to encrypt messages with invalid keys.

**Comment by djhohnstein** [comment]
I haven't looked into the plaintext mode since the initial development cycles so it's definitely possible things got borked. I'll flag it as an action item.

**Comment by its-a-feature** [comment]
Apollo now throws a build error if you try to build without Encryption. It's currently very tightly coupled within how Apollo processes messages, so for the time being you can only build with Encryption.
